[Draft] Increase test coverage
hirosystems/stacks-blockchain-api pull request #1011
Opened 2022-01-31 12:20 UTC by MHassanTariq

## Description

This PR increases the test coverage. It adds test cases that were previously not catered. 

For details refer to issue #985 

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `npm run test` passes
- [ ] Changelog is updated
- [ ] Tag 1 of @rafaelcr or @zone117x for review

2022-02-22 11:19 UTC, MHassanTariq commented
This PR is complete for now. I will make a new PR for rosetta test cases to increase the code coverage.

2022-02-22 12:55 UTC, MHassanTariq commented
@rafaelcr I was trying to rebase this PR. However, one of my tests, [here](https://github.com/hirosystems/stacks-blockchain-api/pull/1011/files#diff-521b3ebceedf4b02e9f0a164d139b5b2cc65fbeae7c5a54d4f5ce265be2bb1e1R8865-R8868), that I added in this PR has been failing. The error shown is 
```
TypeError: Cannot read properties of undefined (reading 'count')
```
This error is generated as the length of rows for [total](https://github.com/hirosystems/stacks-blockchain-api/blob/develop/src/datastore/postgres-store.ts#L2974) is 0. 
Can you suggest anything on how to resolve this?

2022-03-23 00:29 UTC, rafaelcr requested changes

2022-03-23 00:29 UTC, rafaelcr commented on src/datastore/postgres-store.ts
> +      console.log('printing results here: ', results);
Could you remove these debug logs?

2022-03-23 00:29 UTC, rafaelcr commented on src/index.ts
>      switch (process.env['STACKS_BLOCKCHAIN_API_DB']) {
This env variable is now unused. Can you remove it from the entire project?

2022-03-23 00:29 UTC, rafaelcr commented on src/tests/setup.ts
>    const server = await startEventServer({
If I'm not mistaken, this entire global server is never used... Can you try removing it (also removing the db) from here and `teardown.ts` to see if tests are at all affected? If not, we should delete it.

2022-03-24 14:05 UTC, rafaelcr requested changes

2022-03-24 14:05 UTC, rafaelcr commented on src/tests-bns/setup.ts
> -  }
These lines should be kept

2022-03-24 14:05 UTC, rafaelcr commented on src/tests-rosetta/setup.ts
> -  }
Keep these lines too

2022-03-24 14:05 UTC, rafaelcr commented on src/tests-tokens/setup.ts
> -  }
Keep this

2022-03-24 14:05 UTC, rafaelcr commented on utils/src/index.ts
> +  const db = await PgDataStore.connect({ skipMigrations: true, usageName: 'tests' });
```suggestion
  const db = await PgDataStore.connect({ skipMigrations: true, usageName: 'utils' });
```

2022-03-30 14:41 UTC, rafaelcr approved these changes
LGTM 👍 
Before merging, can you change the PR's title to "Remove memory store and increase test coverage"?

2022-03-31 15:09 UTC, rafaelcr approved these changes

2022-03-31 17:27 UTC, merged

2022-04-20 20:07 UTC, blockstack-devops commented
:tada: This PR is included in version 4.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@stacks/stacks-blockchain-api-types/v/4.0.0-beta.1)
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@stacks/blockchain-api-client/v/4.0.0-beta.1)
- [GitHub release](https://github.com/hirosystems/stacks-blockchain-api/releases/tag/v4.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-26 15:49 UTC, blockstack-devops commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@stacks/stacks-blockchain-api-types/v/4.0.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@stacks/blockchain-api-client/v/4.0.0)
- [GitHub release](https://github.com/hirosystems/stacks-blockchain-api/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: