Flaky rosetta tests
hirosystems/stacks-blockchain-api pull request #1103
Opened 2022-03-14 19:14 UTC by MHassanTariq

## Description

This PR separates the rosetta tests from construction tests in `api.ts`. I have also refactored and removed integration for other tests. However, construction tests require integration with `EventServer`, therefore, those are not refactored at all. 

For details refer to issue #123

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [X] Other

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `npm run test` passes
- [ ] Changelog is updated
- [ ] Tag 1 of @rafaelcr or @zone117x for review

2022-03-14 21:08 UTC, rafaelcr commented
@MHassanTariq this looks good, but were you able to find the cause for the flakyness? If the construction tests were not refactored, do we still have a risk of flakyness in those?

2022-03-15 08:22 UTC, MHassanTariq commented
@rafaelcr I initially spent a lot of time diagnosing the actual problem. However, I wasn't able to pinpoint the exact cause as they were not breaking regularly. Therefore, I refactored the tests to the extent where I could remove the maximum integration between them.

2022-03-17 15:59 UTC, rafaelcr commented
Great news @MHassanTariq ... I think the strategy then would be to follow @CharlieC3 's advice and add a mechanism to Github actions that re-tries the test suite if it detects that same error. Can you add that to this PR?

2022-03-17 16:06 UTC, CharlieC3 commented
> Great news @MHassanTariq ... I think the strategy then would be to follow @CharlieC3 's advice and add a mechanism to Github actions that re-tries the test suite if it detects that same error. Can you add that to this PR?

I think the long-term goal would be to use a custom GH runner, or figure out a way to change how the tests are ran to consume less memory. Otherwise besides the retries, we could try running **just these tests** (not the whole pipeline) on a MacOS GH runner. We get fewer of those GH runners, [but they offer double the amount of memory](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

2022-03-18 05:12 UTC, MHassanTariq commented
@rafaelcr sure. I'll look into it.
@CharlieC3 thanks for the suggestion and link!

2022-03-18 05:52 UTC, MHassanTariq commented
@CharlieC3 and @rafaelcr I've tried re-running the tests for `rosetta` once. I think it fixes the problem temporarily like @CharlieC3 mentioned. 
Can you please go through the [changes](https://github.com/hirosystems/stacks-blockchain-api/pull/1103/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR253-R255) in `ci.yml` and let me know if it looks good?

2022-03-22 20:26 UTC, rafaelcr requested changes

2022-03-22 20:26 UTC, rafaelcr commented on src/tests-rosetta/construction.ts
> +  }
Echoing what we discussed on the call, this function could be improved to wait for PoX in a robust way

2022-03-24 14:07 UTC, rafaelcr commented on .github/workflows/ci.yml
> +        if: failure()
This will not be necessary anymore

2022-03-31 15:09 UTC, rafaelcr approved these changes

2022-03-31 19:47 UTC, merged

2022-04-20 20:07 UTC, blockstack-devops commented
:tada: This PR is included in version 4.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@stacks/stacks-blockchain-api-types/v/4.0.0-beta.1)
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@stacks/blockchain-api-client/v/4.0.0-beta.1)
- [GitHub release](https://github.com/hirosystems/stacks-blockchain-api/releases/tag/v4.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-05-26 15:49 UTC, blockstack-devops commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@stacks/stacks-blockchain-api-types/v/4.0.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@stacks/blockchain-api-client/v/4.0.0)
- [GitHub release](https://github.com/hirosystems/stacks-blockchain-api/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: